---
services:

  client:
    container_name: medilynk-client
    build: .
    env_file:
      - .env.production
    ports:
      - "8000:3000"
    
  postgres-db:
    container_name: medilynk-db
    image: postgres:alpine
    restart: unless-stopped
    command: -p 5433
    expose:
      - 5433
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  server:
    container_name: medilynk-server
    image: dgclasher/medilynk-server:latest
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - postgres-db
    env_file:
      - .env
    expose:
      - 4000